# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DW5OdsNwg5rcgceM8OacYo77c2ceB3j8
"""

# 1330
#문제 : 두 정수 A와 B가 주어졌을 때, A와 B를 비교하는 프로그램을 작성하시오.

# 입력
# 1 2

# 출력
# <

a, b = map(int, input().split())
if a > b:
  print('>')
elif a < b:
  print('<')
else :
  print('==')

# 9498
#문제 : 시험 점수를 입력받아 90 ~ 100점은 A, 80 ~ 89점은 B,
# 70 ~ 79점은 C, 60 ~ 69점은 D, 나머지 점수는 F를 출력하는 프로그램을 작성하시오.

# 입력
# 100

# 출력
# A

grd = int(input())
if grd >= 90:
  print('A')
elif grd >= 80:
  print('B')
elif grd >= 70:
  print('C')
elif grd >= 60:
  print('D')
else :
  print('F')

# 14681
#문제 : 점의 좌표를 입력받아 그 점이 어느 사분면에 속하는지 알아내는 프로그램을 작성하시오.
# 단, x좌표와 y좌표는 모두 양수나 음수라고 가정한다.

# 입력
# 12
# 5

# 출력
# 1

x = int(input())
y = int(input())

if x * y > 0 :
  if x < 0 :
    print(3)
  else :
    print(1)
else :
  if x < 0 :
    print(2)
  else :
    print(4)

# 2753
#문제 : 연도가 주어졌을 때, 윤년이면 1, 아니면 0을 출력하는 프로그램을 작성하시오.
# 윤년은 연도가 4의 배수이면서, 100의 배수가 아닐 때 또는 400의 배수일 때이다.

# 입력
# 2000

# 출력
# 1

yr = int(input())

if yr % 4 == 0 and (yr%100 != 0 or yr%400 == 0):
  print(1)
else :
  print(0)

# 2884
#문제 : "45분 일찍 알람 설정하기"

# 입력 : H M (시간은 24시간 표현, 불필요한 0 사용 X)
# 10 10

# 출력
# 9 25

h, m = map(int, input().split())

if m - 45 < 0 :
  m = 60 + m - 45
  if h == 0 :
    h = 23
  else :
    h -= 1
  print(h, m)
else :
  m -= 45
  print(h, m)

