# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1af5ip3RzhGW50E7Od13_lx-vav7OWg4l
"""

# 10952
#문제 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.

# 입력
# 1 1
# 2 3
# 3 4
# 9 8
# 5 2
# 0 0

# 출력
# 2
# 5
# 7
# 17
# 7

while 1 == 1 :
  a, b = map(int, input().split())
  if a != 0 and b != 0:
    print(a + b)
  else :
    break

# 10951 EOF 문제(입력이 끝날 때까지 출력)
#문제 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.

# 입력
# 1 1
# 2 3
# 3 4
# 9 8
# 5 2
# 0 0

# 출력
# 2
# 5
# 7
# 17
# 7

while 1 == 1 :
  try:
    a, b = map(int, input().split())
    print(a + b)
  except:
    break

# 1110
#문제 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
# 26부터 시작한다. 2+6 = 8이다. 새로운 수는 68이다. 6+8 = 14이다. 새로운 수는 84이다. 8+4 = 12이다. 새로운 수는 42이다. 4+2 = 6이다. 새로운 수는 26이다.
# 위의 예는 4번만에 원래 수로 돌아올 수 있다. 따라서 26의 사이클의 길이는 4이다.
# N이 주어졌을 때, N의 사이클의 길이를 구하는 프로그램을 작성하시오.


# 입력 : 첫째 줄에 N이 주어진다. N은 0보다 크거나 같고, 99보다 작거나 같은 정수이다
# 26

# 출력 : 첫째 줄에 N의 사이클 길이를 출력한다.
# 4

count = 0
a = int(input())
b = a

while True:
  if b == a%10 * 10 + (a//10 + a%10)%10: # 몫과 나머지를 원래 값과 비교함
    count += 1
    break
  else:
    count += 1
    a = a%10 * 10 + (a//10 + a%10)%10
print(count)

