# -*- coding: utf-8 -*-
"""day4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DqYtzoMSoeDSZEr4FnHorx_6riLYMts3
"""

# 2739
#문제 : N을 입력받은 뒤, 구구단 N단을 출력하는 프로그램을 작성하시오.
# 출력 형식에 맞춰서 출력하면 된다.

# 입력 : 첫째 줄에 N이 주어진다. N은 1보다 크거나 같고, 9보다 작거나 같다.
# 2

# 출력 : 출력형식과 같게 N*1부터 N*9까지 출력한다.
# 2 * 1 = 2
# 2 * 2 = 4
# 2 * 3 = 6
# 2 * 4 = 8
# 2 * 5 = 10
# 2 * 6 = 12
# 2 * 7 = 14
# 2 * 8 = 16
# 2 * 9 = 18

a = int(input())

for i in range(1,10):
  print(a,'*',i,'=', a*i)

# 10950
#문제 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.

# 입력 : 첫째 줄에 테스트 케이스의 개수 T가 주어진다.
# 각 테스트 케이스는 한 줄로 이루어져 있으며, 각 줄에 A와 B가 주어진다. (0 < A, B < 10)
# 5
# 1 1
# 2 3
# 3 4
# 9 8
# 5 2

# 출력 : 각 테스트 케이스마다 A+B를 출력한다.
# 2
# 5
# 7
# 17
# 7

a = int(input())

for i in range(a):
  a,b = map(int, input().split())
  print(a+b)

# 8393
#문제 : n이 주어졌을 때, 1부터 n까지 합을 구하는 프로그램을 작성하시오.

# 입력 : 첫째 줄에 n (1 ≤ n ≤ 10,000)이 주어진다.
# 3

# 출력 : 1부터 n까지 합을 출력한다.
# 6

a = int(input())
x = 0

for i in range(1, a+1):
  x += i
print(x)

# 8393
#문제 : 
# Python을 사용하고 있다면, input 대신 sys.stdin.readline을 사용할 수 있다.
# 단, 이때는 맨 끝의 개행문자까지 같이 입력받기 때문에 문자열을 저장하고 싶을 경우
# .rstrip()을 추가로 해 주는 것이 좋다.
# 또한 입력과 출력 스트림은 별개이므로, 테스트케이스를 전부 입력받아서 저장한 뒤
# 전부 출력할 필요는 없다. 테스트케이스를 하나 받은 뒤 하나 출력해도 된다.

# 입력 : 첫 줄에 테스트케이스의 개수 T가 주어진다. T는 최대 1,000,000이다.
# 다음 T줄에는 각각 두 정수 A와 B가 주어진다. A와 B는 1 이상, 1,000 이하이다.
# 5
# 1 1
# 12 34
# 5 500
# 40 60
# 1000 1000

# 출력 : 각 테스트케이스마다 A+B를 한 줄에 하나씩 순서대로 출력한다.
# 2
# 46
# 505
# 100
# 2000

#--- sys.stdin 사용한 답안(정답!) : 빠른 처리가 장점
import sys

n = int(input())

a = [tuple(map(int, sys.stdin.readline().rstrip().split())) for i in range(n)]
for i in range(len(a)):
  print(a[i][0]+a[i][1])


#--- input 사용한 답안(NO답!) : 답은 구할 수 있지만 처리가 느림
a = int(input())

if a <= 1000000 :
  for i in range(a):
    a, b = map(int,input().split())
    if a >= 1 and b >= 1 and a <= 1000 and b <= 1000 :
      print(a+b)

# 2741
#문제 : 자연수 N이 주어졌을 때, 1부터 N까지 한 줄에 하나씩 출력하는 프로그램을 작성하시오.

# 입력 : 첫째 줄에 100,000보다 작거나 같은 자연수 N이 주어진다.
# 5

# 출력 : 첫째 줄부터 N번째 줄 까지 차례대로 출력한다.
# 1
# 2
# 3
# 4
# 5

a = int(input())

for i in range(1, a+1):
  print(i)

# 2742
#문제 : 자연수 N이 주어졌을 때, N부터 1까지 한 줄에 하나씩 출력하는 프로그램을 작성하시오.

# 입력 : 첫째 줄에 100,000보다 작거나 같은 자연수 N이 주어진다.
# 5

# 출력 : 첫째 줄부터 N번째 줄 까지 차례대로 출력한다.
# 5
# 4
# 3
# 2
# 1

a = int(input())

for i in reversed(range(1, a+1)): # 값을 역순으로 반환하는 함수 reversed() 
  print(i)