# -*- coding: utf-8 -*-
"""day5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WkvoAI01sXqtadJYTNGpuBgXs1Y79tTA
"""

# 11021
#문제 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.

# 입력 : 첫째 줄에 테스트 케이스의 개수 T가 주어진다.
#  각 테스트 케이스는 한 줄로 이루어져 있으며, 각 줄에 A와 B가 주어진다. (0 < A, B < 10).
# 5
# 1 1
# 2 3
# 3 4
# 9 8
# 5 2

# 출력 : 각 테스트 케이스마다 "Case #x: "를 출력한 다음, A+B를 출력한다.
# 테스트 케이스 번호는 1부터 시작한다.
# Case #1: 2
# Case #2: 5
# Case #3: 7
# Case #4: 17
# Case #5: 7

a = int(input())

for i in range(1,a+1):
  x, y = map(int,input().split())
  print('Case #{}:'.format(i),x+y)

# 11022
#문제 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.

# 입력 : 첫째 줄에 테스트 케이스의 개수 T가 주어진다.
#  각 테스트 케이스는 한 줄로 이루어져 있으며, 각 줄에 A와 B가 주어진다. (0 < A, B < 10).
# 5
# 1 1
# 2 3
# 3 4
# 9 8
# 5 2

# 출력 : 각 테스트 케이스마다 "Case #x: A + B = C" 형식으로 출력한다.
# x는 테스트 케이스 번호이고 1부터 시작하며, C는 A+B이다.
# Case #1: 2
# Case #2: 5
# Case #3: 7
# Case #4: 17
# Case #5: 7

a = int(input())

for i in range(1,a+1):
  x, y = map(int,input().split())
  print('Case #{}: {} + {} = {}'.format(i,x,y,x+y))

# 2438
#문제 : 첫째 줄에는 별 1개, 둘째 줄에는 별 2개, N번째 줄에는 별 N개를 찍는 문제

# 입력 : 첫째 줄에 N(1 ≤ N ≤ 100)이 주어진다..
# 5

# 출력 : 첫째 줄부터 N번째 줄까지 차례대로 별을 출력한다.
# *
# **
# ***
# ****
# *****

a = int(input())

for i in range(1,a+1):
  print('*'*i)

# 2438
#문제 : 첫째 줄에는 별 1개, 둘째 줄에는 별 2개, N번째 줄에는 별 N개를 찍는 문제
# 하지만, 오른쪽을 기준으로 정렬한 별(예제 참고)을 출력하시오.

# 입력 : 첫째 줄에 N(1 ≤ N ≤ 100)이 주어진다..
# 5

# 출력 : 첫째 줄부터 N번째 줄까지 차례대로 별을 출력한다.
# *
# **
# ***
# ****
# *****

a = int(input())

for i in range(1,a+1):
  x = ' '*(a-i)
  y = '*'*i
  print(x+y)

# 10871
#문제 : 정수 N개로 이루어진 수열 A와 정수 X가 주어진다.
# 이때, A에서 X보다 작은 수를 모두 출력하는 프로그램을 작성하시오.

# 입력 : 첫째 줄에 N과 X가 주어진다. (1 ≤ N, X ≤ 10,000)
# 둘째 줄에 수열 A를 이루는 정수 N개가 주어진다.
# 주어지는 정수는 모두 1보다 크거나 같고, 10,000보다 작거나 같은 정수이다.
# 10 5
# 1 10 4 9 2 3 8 5 7 6

# 출력 : X보다 작은 수를 입력받은 순서대로 공백으로 구분해 출력한다.
# X보다 작은 수는 적어도 하나 존재한다.
# 1 4 2 3

n, x = map(int,input().split())
a = list(map(int, input().split()))

for i in range(n):
  if a[i] < x:
    print(a[i], end = ' ')  # sep, end, format, escape 는 print문의 옵션임 / end는 줄바꿈을 하지 않게 됨